"""Initial migration: create all tables

Revision ID: 3dba847fa795
Revises: 
Create Date: 2025-12-04 15:25:27.967772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dba847fa795'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('role', sa.Enum('ADMIN', 'ARCHITECT', 'AUDITOR', 'VISITOR', name='roleenum'), nullable=False, comment='用户角色'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('webhooks',
    sa.Column('id', sa.String(length=50), nullable=False, comment='Webhook ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='系统名称'),
    sa.Column('endpoint_url', sa.String(length=500), nullable=False, comment='推送URL'),
    sa.Column('auth_type', sa.Enum('NONE', 'BASIC', 'BEARER', 'API_KEY', name='authtype'), nullable=True, comment='认证方式'),
    sa.Column('auth_config', sa.JSON(), nullable=True, comment='认证配置'),
    sa.Column('secret_key', sa.String(length=255), nullable=True, comment='签名密钥（加密存储）'),
    sa.Column('request_template', sa.JSON(), nullable=False, comment='请求体模版'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_is_active'), 'webhooks', ['is_active'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=50), nullable=False, comment='API Key ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('key_id', sa.String(length=50), nullable=False, comment='Key标识'),
    sa.Column('secret_hash', sa.String(length=255), nullable=False, comment='Secret哈希'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='最后使用时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_id'), 'api_keys', ['key_id'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='日志ID'),
    sa.Column('user_id', sa.String(length=50), nullable=True, comment='用户ID'),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='操作类型'),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment='资源类型'),
    sa.Column('resource_id', sa.String(length=50), nullable=True, comment='资源ID'),
    sa.Column('changes', sa.JSON(), nullable=True, comment='变更内容'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='User Agent'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.String(length=50), nullable=False, comment='规则ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='规则名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='规则编码'),
    sa.Column('document_type', sa.String(length=50), nullable=True, comment='文档类型'),
    sa.Column('current_version', sa.String(length=20), nullable=True, comment='当前发布版本'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_code'), 'rules', ['code'], unique=True)
    op.create_index(op.f('ix_rules_document_type'), 'rules', ['document_type'], unique=False)
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('value', sa.JSON(), nullable=False, comment='配置值'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='配置描述'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人ID'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('rule_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='版本ID'),
    sa.Column('rule_id', sa.String(length=50), nullable=False, comment='规则ID'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='版本号'),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='rulestatus'), nullable=True, comment='版本状态'),
    sa.Column('config', sa.JSON(), nullable=False, comment='规则配置'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('published_by', sa.String(length=50), nullable=True, comment='发布人ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_versions_status'), 'rule_versions', ['status'], unique=False)
    op.create_table('rule_webhooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='关联ID'),
    sa.Column('rule_id', sa.String(length=50), nullable=False, comment='规则ID'),
    sa.Column('webhook_id', sa.String(length=50), nullable=False, comment='Webhook ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=50), nullable=False, comment='任务ID'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件存储路径'),
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='文件哈希'),
    sa.Column('page_count', sa.Integer(), nullable=True, comment='页数'),
    sa.Column('rule_id', sa.String(length=50), nullable=False, comment='规则ID'),
    sa.Column('rule_version', sa.String(length=20), nullable=False, comment='规则版本'),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'PENDING_AUDIT', 'COMPLETED', 'REJECTED', 'PUSHING', 'PUSH_SUCCESS', 'PUSH_FAILED', 'FAILED', name='taskstatus'), nullable=True, comment='任务状态'),
    sa.Column('is_instant', sa.Boolean(), nullable=True, comment='是否秒传'),
    sa.Column('ocr_text', sa.Text(), nullable=True, comment='合并后的全文'),
    sa.Column('ocr_result', sa.JSON(), nullable=True, comment='完整OCR结果（含坐标）'),
    sa.Column('extracted_data', sa.JSON(), nullable=True, comment='提取的数据'),
    sa.Column('confidence_scores', sa.JSON(), nullable=True, comment='字段置信度'),
    sa.Column('audit_reasons', sa.JSON(), nullable=True, comment='审核原因列表'),
    sa.Column('auditor_id', sa.String(length=50), nullable=True, comment='审核人ID'),
    sa.Column('audited_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('llm_token_count', sa.Integer(), nullable=True, comment='LLM Token消耗'),
    sa.Column('llm_cost', sa.Numeric(precision=10, scale=4), nullable=True, comment='LLM费用'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始处理时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_file_hash'), 'tasks', ['file_hash'], unique=False)
    op.create_index(op.f('ix_tasks_rule_id'), 'tasks', ['rule_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('push_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='日志ID'),
    sa.Column('task_id', sa.String(length=50), nullable=False, comment='任务ID'),
    sa.Column('webhook_id', sa.String(length=50), nullable=False, comment='Webhook ID'),
    sa.Column('http_status', sa.Integer(), nullable=True, comment='HTTP状态码'),
    sa.Column('request_headers', sa.JSON(), nullable=True, comment='请求头'),
    sa.Column('request_body', sa.Text(), nullable=True, comment='请求体'),
    sa.Column('response_headers', sa.JSON(), nullable=True, comment='响应头'),
    sa.Column('response_body', sa.Text(), nullable=True, comment='响应体'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='耗时（毫秒）'),
    sa.Column('retry_count', sa.Integer(), nullable=True, comment='重试次数'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_logs_created_at'), 'push_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_push_logs_task_id'), 'push_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_push_logs_webhook_id'), 'push_logs', ['webhook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_logs_webhook_id'), table_name='push_logs')
    op.drop_index(op.f('ix_push_logs_task_id'), table_name='push_logs')
    op.drop_index(op.f('ix_push_logs_created_at'), table_name='push_logs')
    op.drop_table('push_logs')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_rule_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_file_hash'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('rule_webhooks')
    op.drop_index(op.f('ix_rule_versions_status'), table_name='rule_versions')
    op.drop_table('rule_versions')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_rules_document_type'), table_name='rules')
    op.drop_index(op.f('ix_rules_code'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_webhooks_is_active'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
